import org.jetbrains.kotlin.gradle.dsl.KotlinJsModuleKind

plugins {
    kotlin("js") version "2.1.10"
}

repositories {
    mavenCentral()
}

kotlin {
    js {
        outputModuleName.set("aixodia-worker")
        nodejs()
        // Cloudflare runs the module through workerd, so the output has to be a
        // real ES module with named exports — no Node built-ins, no CommonJS.
        compilerOptions {
            moduleKind.set(KotlinJsModuleKind.ES)
        }
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
}

/**
 * Wrangler wants a module whose default export is the worker object. Kotlin
 * emits the handler as a named export, so the entry module is generated here
 * rather than checked in as another language in the tree.
 */
val bundleWorker by tasks.registering {
    val entry = layout.buildDirectory.file("worker/index.mjs")
    val compiled = layout.buildDirectory.file("dist/js/productionExecutable/aixodia-worker.mjs")
    dependsOn("jsProductionExecutable")
    inputs.file(compiled)
    outputs.file(entry)
    doLast {
        val target = entry.get().asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            // Generated by :bundleWorker — do not edit.
            import { handleFetch } from "../dist/js/productionExecutable/aixodia-worker.mjs";
            export default { fetch: handleFetch };

            """.trimIndent(),
        )
    }
}

tasks.register("buildWorker") {
    group = "build"
    description = "Compiles the Kotlin Worker and writes the wrangler entry module"
    dependsOn(bundleWorker)
}
