plugins {
    kotlin("multiplatform") version "2.1.10"
}

repositories {
    mavenCentral()
}

kotlin {
    js {
        // Cloudflare loads the Worker through workerd, which only speaks ES
        // modules: no UMD wrapper, no CommonJS, no Node built-ins.
        useEsModules()
        nodejs()
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
            }
        }
    }
}

/**
 * Wrangler wants a module whose default export is the worker object. Kotlin
 * emits the handler as a named export, so the entry module is generated here
 * rather than checked in as another language in the tree.
 */
val bundleWorker by tasks.registering {
    val entry = layout.buildDirectory.file("worker/index.mjs")
    val buildDir = layout.buildDirectory
    dependsOn("assemble")
    outputs.file(entry)
    outputs.upToDateWhen { false }
    doLast {
        // The module Gradle emits is named after the project, but the directory
        // layout differs between plugin versions, so the one that actually
        // exports the handler is the one that gets wrapped.
        val root = buildDir.get().asFile
        val modules = root.walkTopDown().filter { it.isFile && it.extension == "mjs" }.toList()
        val compiled = modules.firstOrNull { it.readText().contains("handleFetch") }
            ?: modules.maxByOrNull { it.length() }
            ?: error("no compiled ES module under $root; found: ${modules.map { it.path }}")
        logger.lifecycle("worker: wrapping ${compiled.path}")
        val relative = compiled.relativeTo(entry.get().asFile.parentFile).invariantSeparatorsPath
        val target = entry.get().asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            // Generated by :bundleWorker — do not edit.
            import { handleFetch } from "$relative";
            export default { fetch: handleFetch };

            """.trimIndent(),
        )
    }
}

tasks.register("buildWorker") {
    group = "build"
    description = "Compiles the Kotlin Worker and writes the wrangler entry module"
    dependsOn(bundleWorker)
}
